### ISSUE TITLE
How to delete a previous instance?

### ISSUE THREAD

**Issue by ifndefdeadmau5** [mazlix/meteor-now#30]
Thank you for the awesome work.
I'm using meteor-now with my toy project.
Is there any standard way to re-deploy my project? When I just deploy again through `meteor-now`,  It seems just create another instance which is I'm not going to use anymore.
Thank you for your help, in advance.

**Comment by purplecones** [comment]
Since your Meteor app was deployed to `now`, you can use their commands to manage your deployment. See this [blog post](https://zeit.co/blog/now-rm-is-here-and-more) on their site. 

In short, you can do `now ls` to get a listing of all your deployments.
```
$ now ls

  homepage

      Ai6etlM1hCS6urt      41m ago      https://homepage-jciasjead.now.sh
      0Z6uRTyEs3z8IKD       2h ago      https://homepage-kugudsvdc.now.sh
```

and then run `now rm <id>` to remove any instance you want
```
$ now rm 0Z6uRTyEs3z8IKD
  > The following deployment will be permanently removed:
    0Z6uRTyEs3z8IKD  	  2h ago      https://homepage-kugudsvdc.now.sh
    Are you sure? [Y/N] 
```

As a side note, `now` will always deploy and give you a new instance with a unique url. You can point your deployment to a different url using `now alias`.
```
$ now alias 0Z6uRTyEs3z8IKD abc123
  > Success! Alias created (nC378596z8ArZz7EkfI0z3Rq):
https://abc123.now.sh now points to https://homepage-kugudsvdc.now.sh (0Z6uRTyEs3z8IKD) [copied to clipboard]
```

**Comment by ifndefdeadmau5** [comment]
Wonderful!! It works beautifully.. Thank you for the answer @purplecones  🙏 🙏 🙏
